### ISSUE TITLE
Tracking issue until the Musig2 scheme is implemented

### ISSUE THREAD

**Issue by rjman-ljm** [chainx-org/Musig2#1]
# Tracking issue until the Musig2 scheme is implemented

In simple terms, we need to complete a Musig2 program that can communicate with other nodes in two rounds via network communication to complete the aggregation public key and aggregation signature of the Musig2 scheme.

## Implement Musig2

- [x] #2 
- [x] #3
- [x] #6
- [ ]  Optimization of the aggregate public key and nonce of Musig2
  - [ ] Increase the parity judgment of the aggregate public key, and the signature fragments need to be processed by neg
  - [ ] Optimization of nonce generation method
  - [ ] Checking the code signing process and the latest version of the paper
- [x] #12 
- [ ] Support concurrent signature
